---
resources:
- name: nodejs-shopping-cart-tutorial-master
  type: git
  source:
    uri: https://github.com/vc4017/nodejs-shopping-cart-tutorial-master.git

- name: nodejs-shopping-cart-tutorial-master deploy
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: tovenki.ch@gmail.com
    password: Venki@521
    organization: concourse-node.js app
    space: deployment
    skip_cert_check: true

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: nodejs-shopping-cart-tutorial-master, trigger: true}
  - put: nodejs-shopping-cart-tutorial-master deploy
    params:
      manifest: nodejs-shopping-cart-tutorial-master/manifest.yml
      path: nodejs-shopping-cart-tutorial-master
